[tool.basedpyright]
typeCheckingMode = 'standard'

[tool.pylint.'MESSAGES CONTROL']
disable = ['all']
enable = [
    "access-member-before-definition",
    "anomalous-backslash-in-string",
    "anomalous-unicode-escape-in-string",
    "arguments-differ",
    "arguments-out-of-order",
    "assert-on-string-literal",
    "assert-on-tuple",
    "assign-to-new-keyword",
    "assignment-from-no-return",
    "assignment-from-none",
    "bad-classmethod-argument",
    "bad-classmethod-argument",
    "bad-docstring-quotes",
    "bad-except-order",
    "bad-exception-context",
    "bad-format-character",
    "bad-format-string-key",
    "bad-open-mode",
    "bad-staticmethod-argument",
    "bad-string-format",
    "bare-except",
    "binary-op-exception",
    "blacklisted-name",
    "boolean-datetime",
    "broad-except",
    "c-extension-no-member",
    "catching-non-exception",
    "chained-comparison",
    "comparison-with-callable",
    "comparison-with-itself",
    "confusing-with-statement",
    "consider-merging-isinstance",
    "consider-swap-variables",
    "consider-using-dict-comprehension",
    "consider-using-enumerate",
    "consider-using-in",
    "consider-using-join",
    "consider-using-set-comprehension",
    "consider-using-ternary",
    "cyclic-import",
    "dangerous-default-value",
    "deprecated-method",
    "deprecated-module",
    "dict-iter-missing-items",
    "duplicate-argument-name",
    "duplicate-except",
    "duplicate-key",
    "duplicate-string-formattting-argument",
    "else-if-used",
    "empty-docstring",
    "eval-used",
    "exec-used",
    "expression-not-assigned",
    "f-string-without-interpolation",
    "format-combined-specification",
    "format-needs-mapping",
    "function-redefined",
    "global-at-module-level",
    "global-statement",
    "import-error",
    "import-outside-toplevel",
    "import-self",
    "inconsistent-mro",
    "inconsistent-quotes",
    "inconsistent-return-statements",
    "inherit-non-class",
    "invalid-all-object",
    "invalid-bool-returned",
    "invalid-bytes-returned",
    "invalid-format-index",
    "invalid-format-returned",
    "invalid-getnewargs-ex-returned",
    "invalid-getnewargs-returned",
    "invalid-hash-returned",
    "invalid-index-returned",
    "invalid-length-hint-returned",
    "invalid-length-returned",
    "invalid-metaclass",
    "invalid-name",
    "invalid-overriddent-method",
    "invalid-repr-returned",
    "invalid-sequence-index",
    "invalid-slice-index",
    "invalid-str-returned",
    "invalid-unary-operand-type",
    "isinstance-second-argument-not-valid-type",
    "keyword-arg-before-vararg",
    "len-as-condition",
    "logging-format-truncated",
    "logging-not-lazy",
    "logging-too-few-args",
    "logging-too-many-args",
    "logging-unsupported-format",
    "misplaced-bare-raise",
    "misplaced-format-function",
    "missing-format-argument-key",
    "missing-format-attribute",
    "missing-format-string-key",
    "missing-kwoa",
    "missing-parentheses-for-call-in-test",
    "mixed-format-string",
    "mixed-indention",
    "mutliple-imports",
    "no-classmethod-decorator",
    "no-else-break",
    "no-else-continue",
    "no-else-raise",
    "no-else-return",
    "no-member",
    "no-method-argument",
    "no-name-in-module",
    "no-self-argument",
    "no-staticmethod-decorator",
    "no-value-for-parameter",
    "non-iterator-returned",
    "non-str-assignment-to-dunder-name",
    "not-a-mapping",
    "not-an-iterable",
    "not-callable",
    "not-context-manager",
    "notimplemented-raised",
    "overlapping-except",
    "pointless-statement",
    "pointless-string-statement",
    "possibly-unused-variable",
    "property-with-parameters",
    "protect-access",
    "raising-bad-type",
    "raising-format-tuple",
    "raising-non-exception",
    "redeclared-assigned-name",
    "redefine-in-handler",
    "redefined-argument-from-local",
    "redefined-builtin",
    "redefined-outer-name",
    "redundant-keyword-arg",
    "reimported",
    "relative-beyond-top-level",
    "repeated-keyword",
    "return-arg-in-generator",
    "return-in-init",
    "self-assigning-variable",
    "self-cls-assignment",
    "simplifiable-if-expression",
    "simplifiable-if-statement",
    "singleton-comparison",
    "stop-iteration-return",
    "super-init-not-called",
    "too-few-format-args",
    "too-many-arguments",
    "too-many-format-args",
    "too-many-function-args",
    "too-many-lines",
    "too-many-statements",
    "too-many-try-statements",
    "truncated-format-string",
    "try-except-raise",
    "unbalanced-tuple-unpacking",
    "undefined-all-variable",
    "undefined-loop-variable",
    "undefined-variable",
    "unexpected-keyword-arg",
    "unexpected-line-ending-format",
    "unexpected-special-method-signature",
    "unhashable-dict-key",
    "unidiomatic-typecheck",
    "unnecessary-comprehension",
    "unnecessary-lambda",
    "unnecessary-pass",
    "unneeded-not",
    "unpacking-non-sequence",
    "unreachable",
    "unsubscriptable-object",
    "unsupported-assignment-operation",
    "unsupported-binary-operation",
    "unsupported-delete-operation",
    "unsupported-membership-test",
    "unused-format-string-key",
    "unused-fromat-string-argument",
    "unused-variable",
    "used-before-assignment",
    "useless-else-on-loop",
    "useless-object-inheritance",
    "useless-return",
    "useless-super-delegation",
    "wild-card-import",
    "wrong-exception-operation",
]
